"""empty message

Revision ID: 7ae9625da318
Revises: 5f28fef1aa70
Create Date: 2018-03-04 22:33:18.989927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ae9625da318'
down_revision = '5f28fef1aa70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_game')
    op.drop_table('book')
    op.drop_table('music')
    op.drop_table('movie')
    op.drop_table('comic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comic',
    sa.Column('Comic_ID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('Item_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Item_ID'], [u'item.Item_ID'], name=u'comic_ibfk_1'),
    sa.PrimaryKeyConstraint('Comic_ID'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('movie',
    sa.Column('Movie_ID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('Item_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Item_ID'], [u'item.Item_ID'], name=u'movie_ibfk_1'),
    sa.PrimaryKeyConstraint('Movie_ID'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('music',
    sa.Column('Music_ID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('Item_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Item_ID'], [u'item.Item_ID'], name=u'music_ibfk_1'),
    sa.PrimaryKeyConstraint('Music_ID'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('book',
    sa.Column('Book_ID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('Item_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Item_ID'], [u'item.Item_ID'], name=u'book_ibfk_1'),
    sa.PrimaryKeyConstraint('Book_ID'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('video_game',
    sa.Column('Video_Game_ID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('Item_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Item_ID'], [u'item.Item_ID'], name=u'video_game_ibfk_1'),
    sa.PrimaryKeyConstraint('Video_Game_ID'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
